repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

# Black - Code formatting
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black

# isort - Import formatting
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

# Flake8 - Code quality checks
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
