# This is a basic workflow to help you get started with Actions

name: CI

on:
  - push

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"


jobs:
   run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install linter dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black==22.8.0 isort
      - name: Black
        uses: psf/black@stable
        with:
          options: "--check --verbose --line-length=90"
          version: "~= 22.0"
      - name: Flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Flake8
        run: flake8 --count --show-source --statistics --max-line-length=90 .
      - name: isort
        uses: isort/isort-action@v1.0.0
        with:
          configuration: --profile=black --line-length=90 --check-only --diff
